var insults = [
	"Is your ass jealous of the amount of shit that just came out of your mouth?",
	"Two wrongs don't make a right, take your parents as an example.",
	"If I wanted to kill myself I'd climb your ego and jump to your IQ.",
	"I'd like to see things from your point of view but I can't seem to get my head that far up my ass.",
	"Your family tree must be a cactus because everybody on it is a prick.",
	"Yo're so ugly, when your mom dropped you off at school she got a fine for littering.",
	"It's better to let someone think you are an Idiot than to open your mouth and prove it.",
	"You're proof that god has a sense of humor.",
	"Your birth certificate is an apology letter from the condom factory.",
	'Wife: "I look fat. Can you give me a compliment?" Husband: "You have perfect eyesight."',
	"If laughter is the best medicine, your face must be curing the world.",
	"The only way you'll ever get laid is if you crawl up a chicken's ass and wait.",
	"You must have been born on a highway because that's where most accidents happen.",
	"If ignorance is bliss, you must be the happiest person on earth.",
	"It looks like your face caught on fire and someone tried to put it out with a hammer.",
	"I wasn't born with enough middle fingers to let you know how I feel about you.",
	"If you really want to know about mistakes, you should ask your parents.",
	"What language are you speaking? Cause it sounds like bullshit.",
	"Hey, you have something on your chin... no, the 3rd one down.",
	"If I had a face like yours, I'd sue my parents.",
	"You are proof that evolution CAN go in reverse.",
	"Don't you love nature, despite what it did to you?",
	"So, a thought crossed your mind? Must have been a long and lonely journey.",
	"You're the reason the gene pool needs a lifeguard.",
	"You're so fake, Barbie is jealous.",
	"I'm jealous of all the people that haven't met you!",
	"There's only one problem with your face, I can see it.",
	"I would love to insult you... but that would be beyond the level of your intelligence.",
	"Shock me, say something intelligent.",
	"You are so ugly when you looked in the mirror your reflection walked away.",
	"How many times do I have to flush before you go away?",
	"I don't think you are stupid. You just have a bad luck when thinking.",
	"Hell is wallpapered with all your deleted selfies.",
	"Whats the difference between your girlfriend and a walrus? One has a moustache and smells of fish and the other is a walrus.",
	"Keep talking, someday you'll say something intelligent!",
	"Calling you an idiot would be an insult to all stupid people.",
	"You so ugly when who were born the doctor threw you out the window and the window threw you back.",
	"I would ask you how old you are but I know you can't count that high.",
	"You are living proof that manure can sprout legs and walk.",
	"You're so ugly, you scared the crap out of the toilet.",
	"I may love to shop but I'm not buying your bullshit.",
	"Which sexual position produces the ugliest children? Ask your mother.",
	"I don't know what makes you so stupid, but it really works.",
	"I love what you've done with your hair. How do you get it to come out of the nostrils like that?",
	"Support bacteria - they're the only culture some people have.",
	"You're like school in the summertime - no class.",
	"I'm glad to see you're not letting your education get in the way of your ignorance.",
	"Brains aren't everything. In your case they're nothing.",
	"Ever since I saw you in your family tree I've wanted to cut it down.",
	"I'm multi-talented: I can talk and piss you off at the same time.",
	"Shut up, you'll never be the man your mother is.",
	"Karma takes too long, I'd rather beat the shit out of you just now.",
	"You are so old, when you were a kid rainbows were black and white.",
	"We can always tell when you are lying. Your lips move.",
	"You're about as useless as an asshole with tastebuds.",
	"What would you call a woman who goes out with You? Desperate!",
	"Ordinarily people live and learn. You just live.",
	"I was going to give him a nasty look, but he already had one.",
	"Oh, what? Sorry. I was trying to imagine you with a personality.",
	"It's scary to think that people like you are graduating from college.",
	"You've got two brain cells: one is in a wheelchair and the other one is pushing.",
	"You look like a before picture.",
	"Do you wanna lose ten pounds of ugly fat? Cut off your head.",
	"You're so fat, you could sell shade.",
	"I can feel my personality turning a dull shade of grey when I talk to you.",
	"I can't believe that you were the sperm that won the race, and your still slow.",
	"Looking at you, I understand why some animals eat their young.",
	"If I had a dollar for every time you said something smart, I'd be broke.",
	"Aha, I see the Fuck-Up Fairy has visited us again!",
	"You do realize makeup isn't going to fix your stupidity?"
];


//post random insult
channel.createMessage(insults[Math.floor(Math.random()*insults.length)]);

